#ifndef SDL_GAME_MAP_HPP
#define SDL_GAME_MAP_HPP

#define TILE_SIZE 32

#define MAP_WIDTH 20
#define MAP_HEIGHT 20

#define MAP_TILE_WIDTH (MAP_WIDTH * TILE_SIZE)
#define MAP_TILE_HEIGHT (MAP_HEIGHT * TILE_SIZE)
#define MAP_TILES (MAP_WIDTH * MAP_HEIGHT)

#endif
